package Vista;

import Modelo.VectorEmpleados;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMain
     */
    public VentanaPrincipal() {
        initComponents(); 
        
        VistaUsuarios vista = new VistaUsuarios();
        vista.setSize(984, 462);
        vista.setLocation(0, 0);
        PanelVista.removeAll();
        PanelVista.add(vista, BorderLayout.CENTER);
        PanelVista.revalidate();
        PanelVista.repaint();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVista = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Registro_Bn = new javax.swing.JMenuItem();
        Buscar_BN = new javax.swing.JMenuItem();
        OrdenarSalario_Bn = new javax.swing.JMenuItem();
        OrdenarAlfa_Bn = new javax.swing.JMenuItem();
        OrdenarEstrato_Bn = new javax.swing.JMenuItem();
        Salir_Bn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelVista.setBackground(new java.awt.Color(255, 255, 255));
        PanelVista.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                PanelVistaHierarchyChanged(evt);
            }
        });

        javax.swing.GroupLayout PanelVistaLayout = new javax.swing.GroupLayout(PanelVista);
        PanelVista.setLayout(PanelVistaLayout);
        PanelVistaLayout.setHorizontalGroup(
            PanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        PanelVistaLayout.setVerticalGroup(
            PanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        Registro_Bn.setText("Registrar");
        Registro_Bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registro_BnActionPerformed(evt);
            }
        });
        jMenu1.add(Registro_Bn);

        Buscar_BN.setText("Buscar Imformacion");
        Buscar_BN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_BNActionPerformed(evt);
            }
        });
        jMenu1.add(Buscar_BN);

        OrdenarSalario_Bn.setText("Ordenar Por Salario");
        OrdenarSalario_Bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarSalario_BnActionPerformed(evt);
            }
        });
        jMenu1.add(OrdenarSalario_Bn);

        OrdenarAlfa_Bn.setText("Ordenar Alfabéticamente");
        OrdenarAlfa_Bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarAlfa_BnActionPerformed(evt);
            }
        });
        jMenu1.add(OrdenarAlfa_Bn);

        OrdenarEstrato_Bn.setText("Ordenar Estrato");
        OrdenarEstrato_Bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarEstrato_BnActionPerformed(evt);
            }
        });
        jMenu1.add(OrdenarEstrato_Bn);

        Salir_Bn.setText("Salir");
        Salir_Bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir_BnActionPerformed(evt);
            }
        });
        jMenu1.add(Salir_Bn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Salir_BnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir_BnActionPerformed
        
    }//GEN-LAST:event_Salir_BnActionPerformed

    private void Registro_BnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registro_BnActionPerformed
       /*
        VentanaRegistro vista = new VentanaRegistro();
        vista.setSize(984, 462);
        vista.setLocation(0, 0);

        PanelVista.removeAll();
        PanelVista.add(vista, BorderLayout.CENTER);
        PanelVista.revalidate();
        PanelVista.repaint();
        */
       
    }//GEN-LAST:event_Registro_BnActionPerformed

    private void PanelVistaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_PanelVistaHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelVistaHierarchyChanged

    private void Buscar_BNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_BNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar_BNActionPerformed

    private void OrdenarSalario_BnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarSalario_BnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdenarSalario_BnActionPerformed

    private void OrdenarAlfa_BnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarAlfa_BnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdenarAlfa_BnActionPerformed

    private void OrdenarEstrato_BnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarEstrato_BnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdenarEstrato_BnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem Buscar_BN;
    public javax.swing.JMenuItem OrdenarAlfa_Bn;
    public javax.swing.JMenuItem OrdenarEstrato_Bn;
    public javax.swing.JMenuItem OrdenarSalario_Bn;
    public javax.swing.JPanel PanelVista;
    public javax.swing.JMenuItem Registro_Bn;
    public javax.swing.JMenuItem Salir_Bn;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
